# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b2a06000-462b-4d54-a70a-8b4e219f5e19'
  imageRepository: 'rajatazurepracticenginx'
  containerRegistry: 'devopsazurerepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'latest'

pool:
 name: 'sep29'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build

    steps:
    - script: |
        cp /home/azureuser/.env $(Build.SourcesDirectory)/.env
      displayName: Copy .env file from agent server
          
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)


- stage: RunDockerCompose
  dependsOn: Build  # This ensures Stage 2 runs only after Stage 1
  jobs:
    - job: Deploy
      pool: 
        name: sep29  # Use the name of your self-hosted agent pool
      steps:
        # Checkout the latest code if needed (optional)
        - checkout: self

        # Run docker-compose up in the appropriate directory
        - script: |
            cd /home/azureuser/docker  # Replace with the actual path where your docker-compose.yml is located
            docker compose  up -d  # Run docker-compose to start the containers
          displayName: Run Docker Compose

